# Setup
title:               k
tagline:             '@ jcbsn.dk'
description:         'A personal site about security in tech, kids and friensdship'
url:                 https://k.jcbsn.dk
baseurl:             ''
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Kresten Jacobsen
  url:               https://twitter.com/logiskhave
  email:             k@jcbsn[prik]dk

# Gems
plugins:
  - jekyll-paginate

excerpt_separator: "<!--read_more-->"

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
