# Setup
title:               //kresten
tagline:             '- a personal site'
description:         'A personal site about security in tech, kids and friensdship'
url:                 https://krejac.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kresten Jacobsen
  url:               https://twitter.com/logiskhave
  email:             k@jcbsn[prik]dk

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
