# Setup
title:               k
tagline:             '@ jcbsn.dk'
description:         'A personal site about security in tech, kids and friensdship'
url:                 https://k.jcbsn.dk
baseurl:             ''
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Kresten Jacobsen
  url:               https://twitter.com/logiskhave
  email:             k@jcbsn[prik]dk

# Gems
plugins:
  - jekyll-paginate

# Site specific Jekyll vars
excerpt_separator: <!--more-->
